/**
 * Tailwind theme generated from DESIGN.md (Academic Continuity System).
 * Every token here maps 1:1 to the frontmatter of DESIGN.md — keep them in sync.
 */
// Pretendard covers Hangul and Latin, so one family serves every text role.
const SANS = ['"Pretendard Variable"', 'Pretendard', 'system-ui', 'sans-serif']

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#444653',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#757684',
        'outline-variant': '#c4c5d5',
        'surface-tint': '#3755c3',
        primary: '#00288e',
        'on-primary': '#ffffff',
        'primary-container': '#1e40af',
        'on-primary-container': '#a8b8ff',
        'inverse-primary': '#b8c4ff',
        secondary: '#006c4a',
        'on-secondary': '#ffffff',
        'secondary-container': '#82f5c1',
        'on-secondary-container': '#00714e',
        tertiary: '#4c2e00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#6b4200',
        'on-tertiary-container': '#ffa929',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b8c4ff',
        'on-primary-fixed': '#001453',
        'on-primary-fixed-variant': '#173bab',
        'secondary-fixed': '#85f8c4',
        'secondary-fixed-dim': '#68dba9',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#005137',
        'tertiary-fixed': '#ffddb8',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-fixed': '#2a1700',
        'on-tertiary-fixed-variant': '#653e00',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
      },
      fontFamily: {
        // Korean display face for the site name and hero heading.
        display: ['"Black Han Sans"', ...SANS],
        'headline-xl': SANS,
        'headline-lg': SANS,
        'headline-lg-mobile': SANS,
        'headline-md': SANS,
        'body-lg': SANS,
        'body-md': SANS,
        'label-md': SANS,
        'label-sm': SANS,
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', fontWeight: '800', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max-width': '1200px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'section-gap': '64px',
      },
      maxWidth: {
        container: '1200px',
      },
      boxShadow: {
        // Elevation & Depth — DESIGN.md
        level1: '0px 4px 20px rgba(0, 0, 0, 0.05)',
        'level1-hover': '0px 8px 24px rgba(0, 0, 0, 0.08)',
        level2: '0px 10px 30px rgba(0, 0, 0, 0.1)',
        bar: '0px 1px 8px rgba(0, 0, 0, 0.04)',
        'bar-top': '0px -1px 8px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
}
